# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_nmsum <- function(m) {
    .Call('RSSReQTL_calc_nmsum', PACKAGE = 'RSSReQTL', m)
}

calc_dist <- function(map) {
    .Call('RSSReQTL_calc_dist_exp', PACKAGE = 'RSSReQTL', map)
}

test_calc_shrink <- function(map, Hpanel, Ne, m, cutoff) {
    .Call('RSSReQTL_test_calc_shrink', PACKAGE = 'RSSReQTL', map, Hpanel, Ne, m, cutoff)
}

calc_cov <- function(mat) {
    .Call('RSSReQTL_calc_cov_exp', PACKAGE = 'RSSReQTL', mat)
}

calc_variance <- function(mat) {
    .Call('RSSReQTL_calc_variance_exp', PACKAGE = 'RSSReQTL', mat)
}

cov_2_cor <- function(covmat, rowvar) {
    .Call('RSSReQTL_cov_2_cor_exp', PACKAGE = 'RSSReQTL', covmat, rowvar)
}

calc_shrinkage <- function(distmat, S, hmata, theta, m, Ne, cutoff) {
    .Call('RSSReQTL_calc_shrinkage', PACKAGE = 'RSSReQTL', distmat, S, hmata, theta, m, Ne, cutoff)
}

calcLD <- function(hmata, mapa, m, Ne, cutoff) {
    .Call('RSSReQTL_calcLD_exp', PACKAGE = 'RSSReQTL', hmata, mapa, m, Ne, cutoff)
}

sp_calcLD <- function(hmata, mapa, m, Ne, cutoff) {
    .Call('RSSReQTL_sp_calcLD_exp', PACKAGE = 'RSSReQTL', hmata, mapa, m, Ne, cutoff)
}

orthogonalize_data <- function(data, ortho_covar) {
    .Call('RSSReQTL_orthogonalize_data_exp', PACKAGE = 'RSSReQTL', data, ortho_covar)
}

rssr_orthogonalize_covar <- function(covariates) {
    .Call('RSSReQTL_rssr_orthogonalize_covar', PACKAGE = 'RSSReQTL', covariates)
}

map_eqtl_lm <- function(genotype, expression) {
    .Call('RSSReQTL_map_eqtl_lm_exp', PACKAGE = 'RSSReQTL', genotype, expression)
}

